apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rbs4896qm-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rbs4896qm-java-quarkus 
  name: rbs4896qm-java-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rbs4896qm-java-quarkus 
